---
title: "Tips児童青年版"
output:
  prettydoc::html_pretty:
    theme: leonids
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


-----

## ラポール形成のTips{.tabset}

University of Colorado BoulderのKrollさん,The Ohio State UniversityのSeager van Dykさん らが中心となってまとめて下さった、遠隔医療におけるラポール形成のTipsリストの日本語訳を作成しました。Tips作成のための参考文献もリストされています。成人向け版と児童青年向け版があります。

成人向け版PDFはこちら：[COVID-19 Tips:遠隔医療で成⼈クライエントとのラポール形成](COVID19Tips_Rapport.pdf)

児童青年向け版PDFはこちら：[COVID-19 Tips:遠隔医療で児童青年クライエントとのラポール形成](COVID19Tips_Rapport_CA.pdf)


### 児童青年版

-----

#### COVID-19 Tips: 
#### 遠隔医療で児童青年クライエントとのラポール形成  
Ilana Seager van Dyk, Juliet Kroll, Ruben Martinez, Natacha Emerson and Brenda Bursch  
UCLA Pediatric Psychology Consultation Liaison Service  
https://www.researchgate.net/publication/340066049_COVID-19_Tips_Building_Rapport_with_Youth_via_Telehealth  

> 環境設定  

- 気の散りそうなものはなるべくカメラに映らないようにしてください。また，患者のいる部屋にも，気の散るものができるだけないように保護者にお願いしてください。  

- 若い患者さんはあんまり堅苦しくない部屋を好むでしょうから，患者とビデオカメラ（またはあなたとビデオカメラ）の間に机を置かないほうが良いでしょう。  

- 座り方は子どもの自由にさせましょう。保護者の隣，間，膝，保護者の前の床でもかまいません。  

- 若い患者さんには大きな部屋が良いでしょう。動き回ることができるし，子どもの運動能力，遊び，探索，動きを評価する場合は，そうした活動がカメラのフレーム内に収まるように十分に広いに部屋にすべきでしょう。  

- 十代の方は保護者の同席を嫌がるかもしれませんので，適切なプライバシーが担保されていることを確認するために臨床判断してください（例：誰にも聞かれていないと患者さんが安心できているかを尋ねる）。患者が映像での通信を嫌がってるなら，テキストやチャットを使うのも良いでしょう。11歳以上の子に特に役立つかもしれません。  

- 患者さんがあなたの表情を見ることができるように，カメラがちゃんと「ズームイン」されているかを確認してください。  

- ずっとカメラを見ておくようにしましょう。コンピュータやメモに目をそらさないでください。  

- 可能であればピクチャー・イン・ピクチャー機能を使いましょう（例：自分と患者さんの両方を画面に映す）。それで，自分がどんなふうに見えているか，自分の背景に気の散るものがないか（たとえば，飼い猫とか！）を確認しましょう。  

- 患者さんは，背景機能を使って遊ぶことができます。これは患者さんにコントロール感を与えます。次回のセッションの「場所」を患者さんに選択してもらっても良いかもしれません（たとえば，宇宙空間や，好きな場所の背景画像をアップロードして使用してもらうなど）。  

> 患者さんに遠隔医療を紹介する方法（Glueck, 2013からの抜粋）  

以下の推奨事項は，患者さんの発達年齢によって調整してください。  

- 患者さんが電話やパソコンを使って医師に診てもらったことがあるかどうかを尋ねます。患者さんが遠隔医療を使用したことがない場合は，一般的な遠隔サービスの技術（Facetime，Skype，Zoomなど）を参考にして，主な違いを説明すると良いでしょう。  

- 遠隔医療を使う理由を患者さんに知ってもらいましょう。たとえば，「私たちは，COVID-19で大変な今も患者さんと会うために，遠隔医療サービスの技術を使っています。そのようにして，皆さんができるだけ元気でいられるようにしています」とか，「これを使ってるので，今日あなたに会うためにフェイスマスクを使用する必要はありません」などの説明ができるでしょう。  

- 必要であれば，セッションがリアルタイムで行われていることを患者さんに伝えてください。「あなたが私について見えているのと同じように，私もあなたを見ることが出来ます。たとえば，あなたは○○○を着ていますね」とか「あなたは今〇〇〇しましたね」などと患者さんのジェスチャーや身につけているものについてコメントすることによってそのことを示すことができるでしょう。特に子どもたちはこうしたことを喜びますし，見てもらっているという証拠になります。  

- 必要なら，セキュリティについても話しましょう。たとえば，十代の若者たちは，HIPAA（医療保険の相互運用性と説明責任に関する法律）の標準である暗号化技術の問題を理解しているかもしれません。小さい子どもが誰かに会話を盗み聞きされていることを心配したら，「こっちのカメラからそっちのカメラは電子のトンネルで繋がってるんだよ」などと説明すると良いでしょう。要望があれば，技術的な仕様について追加で説明出来るようにしておきましょう。患者さんの中には，セッションが一般に公開されていないという意味で「インターネット上」ではないことに安心させてくれることに感謝している人もいます。  

- セッションが録音・録画される場合には患者さんに知らせることが重要です。録音・録画には患者さんから明確な同意を得る必要があります。十代の患者さんは，録画された内容の中で何を親に共有されるのか（例：薬物使用，性行為）について情報があればありがたいと思うでしょう。必要に応じて，強制開示について説明してください。録音・録画がスーパービジョンのみを目的としているのであれば，プライバシー侵害の不安を和らげるために，それを家族にも伝えてください。  

- 自分の部屋の様子を患者さんに教えてあげてください。患者さんにオフィスを見たいか尋ねます。カメラのズームやカメラを左右に向ける機能を使ったり，デバイスを手動で動かすことで，患者さんに職場のバーチャルツアーを体験してもらうと同時に，他に誰もいないことを確認してもらいます。ツアーの後には，カメラをズームにして，患者さんがあなたの表情を確認できることを伝えます。  

- 最初に話している中で技術的な問題が発覚したら，すぐに話し合ってください。たとえば，話してると音声にわずかな遅れがあるなら，発言の後に少し間を置くように提案してみてもよいでしょう。テレビ会議システムに慣れるためには時間がかかることを強調し，「お互いに発言を被せて話さないように」ということを強調します。  

- セッションを始める前に患者さんに質問する機会を与えてください。これは，電子メディアに慣れていない若い患者さんや高齢の患者さんには特に大切です。  

> ラポールの形成

- 遠隔医療の形式によっては，患者さんが「誰かの話を中断したり，割り込んだり」できないので，患者さんが話す機会をきちんと確保して，会話の主導権があることを伝えてください。  

- ワークシートやその他の視覚的な活動を使ったり作成しているのなら，患者さんに色やフォントや写真を選ばせてあげるのも良いです。ある程度のコントロールを与えます。  

- 若者を惹きつけるために，大げさな表現や身振りを使うのも良いでしょう（例：仮想的なハイタッチ，親指を立てる）。  

- 発言の要約，リフレクション，観察をよくよく使って，自分が話を聞いていることを患者に示してください。  

- 支援の手続きについては，お互いに理解していることを言語的に確認してください（例：リラクセーションやエクスポージャーの根拠）。  

- 子どもたちはお絵かきで楽しんでもらうと良いでしょう。カメラを通してお話しながら絵を共有すると良いです。その絵は，子どもの注意力，細かい運動スキル，創造性を評価するのにも役立つかもしれません。また，人形遊び（例：お人形，アクションフィギュア）も，象徴遊びの能力や思考の内容を知るのにも使えます。  

- 邪魔にならないもので，小さい子どもに家の中で好きなもの（おもちゃ，本，毛布など）を教えてもらうようにしても良いです。描いた絵をカメラにかざして説明してもらっても良いです。  

- 年長さんの場合は，絵や日記，音楽など，共有できるものがないかどうかを尋ねてみてください。青年期の子にもYouTubeやFacebookなどのオンラインサイトを利用して興味を持ってもらうことを検討してみましょう。  

- 子どもや十代の若者は，臨床医と知り合いになることにも嬉しがるかもしれません。簡単なQ&Aでお互いの自己紹介をしましょう（例：「好きなテレビ番組は何ですか？」，「好きな色は何ですか？」，「好きな食べ物は何ですか？」，「兄弟は何人いますか？」）。  

- オンラインセッションで初めのほうは，患者の発言の解釈で断定的に発言するのを避けたり，開かれた質問や比喩的な表現の使用が役立つかもしれません。  

- くだけた言葉を使うようにするなど，若者の言語パターンを反映し，ラポールを脅かすようなことがあれば純粋さをもって対処しましょう。  

- シンプルに患者さんと会話をしてください！これは遠隔医療であっても信頼できるラポール形成の方法です。  

- 忍耐とユーモアをもって，遠隔医療に関連する避けられない技術的・臨床的問題を乗り切りましょう。  

> 子どものやる気を維持する

- 芸術療法は，若い患者さんにやる気になってもらうために有効かもしれません。患者さんにカメラで写真を撮ってきてもらったり，画面共有オプションを使って一緒にアートを作ったりすることができます（利用しているプラットフォームによって利用できる機能が異なります）。  

- あなたの使用しているプラットフォームで機能できるのであれば，配布資料を共有して共同で作業することも考慮してみましょう（例：編集可能なドキュメントやパワーポイントをZoomで画面共有して使用する）。  

- エンゲージメントを高めるために様々な機能を利用してみてください（例：Zoomには「ホワイトボード」という，患者と臨床医が一緒に絵を描いたり，マルバツゲームができる機能があります）。プラットフォームの機能に関する具体的なトレーニングやヒントについては，各サイトのテクノロジーサービスへ確認してください。  

- 小さな子どもとのセッションでは，部屋におもちゃがあることは問題ありませんが，音質の妨げになる大きな音が出るおもちゃや騒がしいおもちゃは避けるように保護者に頼んでください。必要に応じて，エンゲージメントを高めるために保護者に手伝ってもらいましょう。  

- 多動な子どもや自閉症の子どもは，フレーム内に留まることが難しい場合があります。保護者にフレームの中に入っておいてもらい，質問に答えてもらうときに子どもを呼んでもらうようにすることも検討してください。  

- 不安な子どもや反抗的な子どもがカメラのフレーム内に座ることを拒否する場合は，まず典型的な行動管理法を使ってみてください。また，次のセッションの前に，保護者に，セルフモニターの画像をオフにして，その子をフレーム内におさまるようにカメラから遠く離れた場所に座らせるように依頼します。他にも，セッションの一部でその子のプライバシーを担保するのもよいです。  

- 特に小さい患者さんは，遠隔医療に参加し続けることが難しいという認識を持ちましょう。参加し続けてもらうことに苦労するようであれば，セッションの長さについて期待値を調整してください。  

- 近年では，遠隔医療に対する若者の満足度は，繰り返し使用することで高まると言われています。最初は遠隔医療に不安を感じていた若者も，10～15分ほどで苦痛が軽減されたことが示されています。  

- 一連の治療を通して，技術的な難しさ，独自の課題，または遠隔医療を行うことで得られる利点に関する会話を継続することが重要です。質問を続けましょう！  

> 参考文献  

Boydell, K. M., Volpe, T., & Pignatiello, A. (2010). A qualitative study of young people’s perspectives on receiving psychiatric services via televideo. Journal of the Canadian Academy of Child and Adolescent Psychiatry = Journal De l’Academie Canadienne De Psychiatrie De L’enfant Et De L’adolescent, 19(1), 5–11.   
  
Gloff, N. E., LeNoue, S. R., Novins, D. K., & Myers, K. (2015). Telemental health for children and adolescents. International Review of Psychiatry, 27(6), 513–524.   https://doi.org/10.3109/09540261.2015.1086322  
  
Glueck, D., Myers, K., & Turvey, C. (2013). Establishing therapeutic rapport in telemental health. In Telemental health: Clinical, technical and administrative foundations for evidence-based practice (pp. 29–46).   
  
Goldstein, F., & Glueck, D. (2016). Developing Rapport and Therapeutic Alliance During Telemental Health Sessions with Children and Adolescents. Journal of Child and Adolescent Psychopharmacology, 26(3), 204–211.   https://doi.org/10.1089/cap.2015.0022 
  
Myers, K. M., Valentine, J. M., & Melzer, S. M. (2008). Child and Adolescent Telepsychiatry: Utilization and Satisfaction. Telemedicine and E-Health, 14(2), 131–137. https://doi.org/10.1089/tmj.2007.0035  
  
Myers, K., Nelson, E.-L., Rabinowitz, T., Hilty, D., Baker, D., Barnwell, S. S., Boyce, G., Bufka, L. F., Cain, S., Chui, L., Comer, J. S., Cradock, C., Goldstein, F., Johnston, B., Krupinski, E., Lo, K., Luxton, D. D., McSwain, S. D., McWilliams, J., … Bernard, J. (2017). American Telemedicine Association Practice Guidelines for Telemental Health with Children and Adolescents. Telemedicine and E-Health, 23(10), 779–804. https://doi.org/10.1089/tmj.2017.0177   
  
Nelson, E.-L., & Patton, S. (2016). Using Videoconferencing to Deliver Individual Therapy and Pediatric Psychology Interventions with Children and Adolescents. Journal of Child and Adolescent Psychopharmacology, 26(3), 212–220. https://doi.org/10.1089/cap.2015.0021   
  
Rockhill, C., & Goldstein, F. (n.d.). Child & Adolescent Telepsychiatry: Developing a Virtual Therapeutic Space. American Psychiatric Association. Retrieved March 17, 2020, from https://www.psychiatry.org/psychiatrists/practice/telepsychiatry/toolkit/child-adolescent/developing-a-virtual-therapeutic-space   
  
Roth, D. (n.d.). Child & Adolescent Telepsychiatry: Participant Arrangement. American Psychiatric Association. Retrieved March 17, 2020, from https://www.psychiatry.org/psychiatrists/practice/telepsychiatry/toolkit/child-adolescent/participant-arrangement   
  
Timm, M. (2011). Crisis counselling online: Building rapport with suicidal youth.　https://doi.org/10.14288/1.0054473  
  

> 翻訳者

小林智之 (福島県立医科大学災害こころの医学講座)  
佐藤秀樹 (福島県立医科大学災害こころの医学講座)  
高階光梨 (緑樹会 やまうちクリニック)  
竹林由武 (福島県立医科大学健康リスクコミュニケーション学講座)  

-----