---
title: "Tips"
output:
  prettydoc::html_pretty:
    theme: leonids
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## ラポール形成のTips

Colorado Boulder大学のKrollさんらが中心となってまとめて下さった、遠隔医療におけるラポール形成のTipsリストの日本語訳を作成しました。Tips作成のための参考文献もリストされています。

PDFはこちら：[COVID-19 Tips:遠隔医療で成⼈クライエントとのラポール形成]("https://github.com/ytake2/APA_telepsychology_evidence_list/blob/master/COVID19Tips_Rapport.pdf")


-----

### COVID-19 Tips: 遠隔医療で成人クライエントとのラポール形成

Juliet Kroll, Ruben Martinez, and Ilana Seager van Dyk  
UCLA Pediatric Psychology Consultation Liaison Service  

https://www.researchgate.net/publication/30414789_COVID-19_Tips_Building_Rapport_with_Adults_via_Telehealth  

  

> 環境設定  

- クライエントと映像通信を行う空間内のカメラで映るところに，注意が削がれそうな物ができるだけ映り込まないようにしてください。可能なら，最初はピクチャーインピクチャー機能（たとえば，患者さんと対話している自分の顔も表示される機能）を使用して，患者さんから自分がどのように見えているか，背景に注意が削がれるような物がないかを確認してください。  

- 同様に，患者さん側にも注意が削がれそうなものは極力映り込まないようにしてもらいましょう。「画面の外」には集中を阻害する刺激が普通にあること（犬，車，パートナー，家族など）を認識し，電話をサイレント（マナー）モードにする，他のブラウザを閉じるなどを患者さんに促してください。  

- 適切にプライバシーが守られるように臨床判断をしましょう（たとえば，自分のいる空間やセラピスト側の「画面の外」などで，患者さんが誰にも会話を聞かれていないと安心できているかどうか）。完全にプライベートな空間が担保できない場合は，ヘッドフォンを使用するとよいでしょう。   

- 患者さんからあなたの表情が見えて，あなたからも患者さんの表情が見えるように，映像が十分に「ズームイン」されていることを確認してください。  

- 必要に応じて，面接中は帽子や大きなスカーフを外すように患者さんにお願いするとよいでしょう。ビデオ通話のシステムの性質上，患者さんが発する非言語的なサインが帽子やスカーフによって（覆い隠されてしまい，セラピストが）気付きにくくなってしまう可能性があります。  

- パソコン（スクリーン）やメモばかり見ずに，常にカメラに目線を向けるようにしてください。  

- セラピストと患者さんが面接の画面に互いに適切に収まった後は，患者さんにピクチャーインピクチャー機能をオフにすることを提案してもよいでしょう。そうしないと，患者の気が散ってしまって，強い感情を共有したりすることが難しくなる可能性があります。これは，ボディイメージに不安を感じている患者さんや，セラピーを始めて間もない患者さん，感情的に警戒心が強い患者さんとやりとりをする場合には特に重要です。患者の視線が何度も画面の隅に向いていることに気づいたら，患者は自分自身を見ている可能性があります。その場合，画面の電源を切るように促してください。ただし，グループセッションでは他の患者も多くいるので，この方法はあまり重要ではないかもしれません。  

- 患者さんにセラピストの声が大きすぎると感じていないかどうか確認してください。これは，通話中にエコーを発生させたり，患者のプライバシーを低下させたり，あるいは単純に患者さんにとって不快である可能性があります。  

- 不意にドアをノックする音がした場合に備えて，セラピストと患者さんが通話をミュートにする方法がわかっているか確認してください。  

- 映像の接続が悪く解像度の低い映像が表示される場合は，電話に切り替えるために閾値を低く設定してください。  

- 緊急事態に備えた計画について確認しましょう（患者がいる場所の緊急サービスの連絡先を含め，管理責任者やチームメンバーと話し合って理解しておきましょう）。患者の緊急連絡先を確認し，いざ緊急時に使用できるよう，患者さんの自宅に患者さん以外の誰かがいるかどうかを確認してください。   

- 遠隔医療システムが機能しなくなった緊急時に備えるための，対応計画を立てましょう（例：臨床家が別のセッションを開始するために電話に移行する）。  

> 患者への遠隔医療の導入 (Lozano et al., 2015からの抜粋)  

- 遠隔医療に不慣れな患者さんとやりとりをする際には，初回セッションの開始前に必ず電話をして，遠隔技術に関する説明を行うことをお勧めします。  

- 患者さんが電話やコンピュータを使って医師の診察を受けたことがあるか尋ねます。患者さんが遠隔医療を使用したことがない場合は、一般的な遠隔サービス（アプリ）（Facetime、Skype、Zoomなど）を参考にして、主な違いを説明するとよいでしょう。  

- なぜ遠隔医療の面接が実施されているのかについて患者さんが理解できるように簡潔にお伝えしましょう。例えば，"精神保健の臨床医は，COVID-19の発生下において，誰もが可能な限り健康でいられるように，通信技術を使って患者さんの診察をしています"。適切な場合には, 対面で治療を再開するか，遠隔医療を利用して治療を継続するかどうかを患者さんに伝えます。   

- 必要に応じてセキュリティについて話し合いましょう。暗号化技術にはHIPAA（Health Information Portability and Accountability Act）が推奨されていますが，COVID-19発生時には，HIPAAのガイドラインが完全に施行されるとは限りません(訳注:一時的に規制緩和がなされ基準が平時よりも緩くなる場合があります）。適切なプラットフォームについては，地域の行政機関に確認してください。   

- 患者さんに、自傷他害についての危機対応を含め，対面での治療と同じ法的保護と守秘義務の制限が遠隔医療にも適用されることを伝えましょう。   

- 機関によっては，遠隔医療のために，面接時に毎回口頭で同意を得て，その同意を文書として保存することを要求される場合があります。セッションを記録する場合には，患者さんからはっきりとした同意を得なければなりません。  
- 遠隔医療による面接テレヘルスセッションへのアクセス方法についての（イラストが掲載された）書面による教示と遠隔技術の使い方の練習を優先して行ってください。高齢者の場合は，面接にアクセスするために必要なステップが最小限となるように配慮しましょう。例えば、Zoomを使用する場合は、招待状全体ではなく、会議に参加するためのURLや電話番号を1つだけ送ることを検討してください。  

- 技術的な問題が発生した場合はすぐに，また治療中にも適宜，技術的な問題（例：音量の大きさが適切であるか、エコーが効きすぎて聞こえづらくないかなど)について話し合いましょう。例えば，音声の遅延に直面している場合は，ゆっくりと話すことが有用であるかもしれません。   

- セッションを始める前に患者さんに質問する機会を十分に与え，慣れるまでに時間がかかるかもしれないことや"技術を一緒に学ぶ機会である "ことをノーマライズしてください。患者さんが過去に受けた遠隔医療の経験，遠隔医療に関する現在の考えや態度，モダリティに関して患者さんが抱えているかもしれない疑問について話し合ってください。  

- 遠隔医療を介した治療は対面に劣る第二の治療オプションではなく，治療を提供するための最先端のアプローチであることを明確に伝えましょう。多くの研究では，遠隔医療を介して提供される治療が、対面セッションと同等の効果があることが実証されています。   

> ラポールを築く  

- いつものように，思いやりのある挨拶と導入をしてください。つまり，まず注意を向けるべきなのはあなたと患者さんについてであり，技術ではありません。  

- 技術的な問題が起こったとしても，慌てて見えないようにして患者さんに注意を向けてください。  

- いくつかの遠隔医療の形式では，患者さんが会話を中断したり，誰かに話しかけたりすることが困難です。そのことを考慮して，患者さんが話す機会を提供したり，会話をコントロールしたりしてください。  

- 技術的な問題（例：通話中にエコーがかかる，患者さんの声が小さい）が発生している場合は，セッション中にできるだけ早く対処するようにしてください。同様に，患者さんにあなたの声がはっきりと聞こえているかどうかについても確認してください。  

- 遠隔医療を実施している際には，(ちいさな非言語的情報など)コミュニケーションのニュアンスが失われてしまう可能性があります。必要に応じて大げさな表現やジェスチャーを用いるようにし、患者さんがあなたの身振り手振りを見ることができるように，カメラから十分に離れた場所に座ることを検討してください。患者さんをよりはっきりと観察する必要のある治療ターゲットに取り組んでいる場合（例：患者さんのチック症状の観察）は，患者さんにカメラから離れた場所に座ってもらい、デモンストレーションを行うときにもさらに後ろに座って行います。   

- 要約，リフレクション，観察を頻繁に使用して，患者さんにあなたが話を聞いていることを再認識させます。  

- 対面での支援よりも治療中に行われていること（例：リラクセーションの理論的根拠，エクスポージャー）について相互理解するために口頭で確認を多く行うようにします。  

- 患者さんの言語パターンを反映させ，ラポールを脅かすような場面にも真摯に対応するようにしましょう。対面でのセッションで行うのと同じように，ボディランゲージを使ってこちら側の関与を相手に示すことができます（例えば，強化したい内容に応じて，カメラに近づいたり遠ざけたりします）。  

- 遠隔医療は、臨床家と患者間の「力の不均衡」の解消に役立つかもしれません。  

- 臨床家は，クライアントが認識する以上に，ラポール形成が良好ではないと報告しがちなことに注意が必要です。患者さんと単にやりとりをするだけでも，遠隔医療であれ信頼できるラポール形成につながります。    

- 何より，遠隔医療に関連する避けられない技術的・臨床的な課題に対して，忍耐とユーモアをもって乗り切りましょう。  

> 患者の関与を維持する  

- あなたが実施する治療に関わるならば，セッション中に実施する活動（例：内部感覚エクスポージャー）に適した広さがある面接ための場所を，患者さんが確保できるように支援します。  

- 患者さんと協力して，セッション中の評価や介入に関連する資料マテリアル（例：質問紙、面接の配布資料）を，ビデオ会議システムの画面共有を介して，または電子メール，ファックス，（必要に応じて）郵便を利用して共有する方法を考えます。配布資料を使用することや心理教育を繰り返し行うことは，患者の気がそれやすい遠隔医療では特に重要になるかもしれません。   

- 配布資料を(事前に)共有する，あるいは面接中に画面共有を介して(患者さんと)やりとりすることを検討してください。Zoomでは，共有機能の下にあるホワイトボードを使用して，患者さんに概念について説明することができます。また，Zoomでは画面共有を介して患者さんとセラピストの両方が文書に注釈を付けることができます。  

- 研究によれば、遠隔医療やグループのラポールに対する満足度は，繰り返し使用する中で向上していくことが示されています。最初は遠隔医療に不安を感じていた患者さんでも，初回のセッション後には苦痛が減少したと報告されています。実際，クリニックの環境のほうがより不安を感じる患者さんにとっては、自宅でセッションを行う方がより快適に感じるようです。  
- 患者さんの中には，リラクセーションやイメージエクササイズが遠隔医療を通じて「遠く」感じると報告する人もいます。ガイド付きのエクササイズに「慣れる」ことの一環として，患者さんに音量設定を確認したり，音量を上げたりすることを奨励することができます。   

- 適切な場合は，画面共有機能を使って魅力的な動画や映像コンテンツを使用します。  

- 患者さんが自宅にいることの利点を治療的介入の中で活用してください。例えば，コーピングキット（クラインと個別のコーピングのリスト）を作成する際には，セッション中に患者さんに各コーピングを集めてもらうことができます。また，マインドフルネスや癒しの活動の一環として，ペットや患者自身が作曲した音楽を使用することもできます。  

- 一連の治療を通して，技術的な難しさ，独自の課題，または遠隔医療を行うことで得られる利点に関する会話を継続することが重要です。質問を続けましょう！  

> グループ療法実施のヒント  

- 臨床家が一度にすべてのグループメンバーを簡単に画面に表示できるように，グループのメンバーを5～7人に制限するようにしましょう。  
- 一部のプラットフォーム（Zoomなど）では，会議の司会者が参加者の音声をミュート(消音)にしたり，ペアや少人数でグループワークを行うために参加者を「ブレイクアウトルーム」を割り当てたりすることができます。これは，個々のサイドバーでの会話（例えば、zoom通話中のチャット画面での会話など）がそれほど簡単にはできない場合に，グループメンバー間の親密な関係を構築するのに役立ちます。   

- セッション中にメンバー間でのクロストークやその他の有益でない議論を最小限に抑えるために，「チャット」機能を監視しましょう。患者さんには，個人的にチャットをしないように促してください。  

- グループメンバー全員に向けて（発言や）共有をしたい時以外は音声をミュートにしておくように頼むと，周囲の雑音など気が散ることが減るかもしれません。患者が周囲の雑音なしに無音で参加することができれば，より流動的で自然な反応や質問への応答が可能になるでしょう。  

> 参考文献  

Foster, M. V., & Sethares, K. A. (2014). Facilitators and barriers to the adoption of telehealth in older adults: an integrative review. CIN: Computers, Informatics, Nursing, 32(11), 523-533.   

Gloff, N. E., LeNoue, S. R., Novins, D. K., & Myers, K. (2015). Telemental health for children and adolescents. International Review of Psychiatry, 27(6), 513–524. https://doi.org/10.3109/09540261.2015.1086322  

Glueck, D., Myers, K., & Turvey, C. (2013). Establishing therapeutic rapport in telemental health. In Telemental health: Clinical, technical and administrative foundations for evidence-based practice (pp. 29–46).   

Goldstein, F., & Glueck, D. (2016). Developing rapport and therapeutic alliance during telemental health sessions with children and adolescents. Journal of Child and Adolescent Psychopharmacology, 26(3), 204–211. https://doi.org/10.1089/cap.2015.0022   

Grady, B., Myers, K. M., Nelson, E. L., Belz, N., Bennett, L., & Carnahan, L. (2011). American Telemedicine Association Telemental Health Standards and Guidelines Working Group. Evidence-based practice for telemental health. Telemed JE Health, 17(2), 131-148.   

Grady, B., & Singleton, M. (2011). Telepsychiatry “coverage” to a rural inpatient psychiatric unit. Telemedicine and eHealth, 17(8), 603-608. *Specific considerations regarding efficacy of inpatient management   

Gros, D. F., Morland, L. A., Greene, C. J., Acierno, R., Strachan, M., Egede, L. E., ... & Frueh, B. C. (2013). Delivery of evidence-based psychotherapy via video telehealth. Journal of Psychopathology and Behavioral Assessment, 35(4), 506-521.   

Kovaleva, M., Blevins, L., Griffiths, P. C., & Hepburn, K. (2019). An online program for caregivers of persons living with dementia: Lessons learned. Journal of Applied Gerontology, 38(2), 159-182.   

Jenkins-Guarnieri, M. A., Pruitt, L. D., Luxton, D. D., & Johnson, K. (2015). Patient perceptions of telemental health: systematic review of direct comparisons to in-person psychotherapeutic treatments. Telemedicine and e-Health, 21(8), 652-660.  

Lozano, B. E., Birks, A. H., Kloezeman, K., Cha, N., Morland, L. A., & Tuerk, P. W. (2015). Therapeutic alliance in clinical videoconferencing: Optimizing the communication context. In Clinical Videoconferencing in Telehealth (pp. 221-251).  

Springer, Cham. Myers, K., Nelson, E.-L., Rabinowitz, T., Hilty, D., Baker, D., Barnwell, S. S., Boyce, G., Bufka, L. F., Cain, S., Chui, L., Comer, J. S., Cradock, C., Goldstein, F., Johnston, B., Krupinski, E., Lo, K., Luxton, D. D., McSwain, S. D., McWilliams, J., Bernard, J. (2017). American Telemedicine Association Practice Guidelines for Telemental Health with Children and Adolescents. Telemedicine and E-Health, 23(10), 779–804. https://doi.org/10.1089/tmj.2017.0177  

Simpson, S., Bell, L., Knox, J., & Mitchell, D. (2005). Therapy via videoconferencing: A route to client empowerment?. Clinical Psychology & Psychotherapy, 12(2), 156-165. Timm, M. (2011). Crisis counselling online: Building rapport with suicidal youth. https://doi.org/10.14288/1.0054473  


> 翻訳者  

青木俊太郎 (福島県立医科大学医療人育成・支援センター)  

樫村正美 (日本医科大学医療心理学教室)  

小林智之 (福島県立医科大学災害こころの医学講座)  

佐藤秀樹 (福島県立医科大学災害こころの医学講座)  

高階光梨 (緑樹会 やまうちクリニック)  

竹林由武 (福島県立医科大学健康リスクコミュニケーション学講座)






